app/routes.py
# app/routes.py

from flask import Blueprint, render_template, redirect, url_for, flash, request, send_file, current_app, abort, session, g, jsonify
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User
from app.models import Project
from app.models import MosaicTiles
from app.models import MosaicTargetImages
from app.models import MosaicPreviewImages
from app.models import Mosaic

from MosaifyPy import Image
from MosaifyPy import MosaifyPy

from PIL import Image
import mimetypes
import io
import os
import uuid
import zlib

from app.common import find_number_in_array


import platform

import logging
logging.basicConfig(level=logging.DEBUG)

# print("Printing Platform")
# print(platform.uname())

main = Blueprint('main', __name__)

@main.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']
        hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
        user = User(username=username, email=email, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created!', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html')

@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.query.filter_by(email=email).first()
        if user and bcrypt.check_password_hash(user.password, password):
            login_user(user)
            flash('You have been logged in!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html')

@main.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.login'))

@main.route('/home')
@login_required
def home():
    all_projects = Project.query.filter_by(user_id=current_user.id).all()
    projects = [proj for proj in all_projects]
    return render_template('home.html', projects=projects)

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/list')
@login_required
def list_files():
    # Query the MosaicTiles table for all filenames
    filenames = MosaicTiles.query.with_entities(MosaicTiles.filename).all()
    # Extract filenames from the result tuples
    files = [file.filename for file in filenames]
    files.sort()

    current_project_id = session['current_project_id']
    filenames = MosaicTiles.query.with_entities(MosaicTiles.filename, MosaicTiles.id).filter_by(project_id=current_project_id).all()
    files = [file.id for file in filenames]

    return render_template('list.html', files=files)

@main.route('/preview_tilefile/<id>')
@login_required
def preview_tilefile(id):
    file_entry = MosaicTiles.query.filter_by(id=id).first()

    if file_entry:
        x = file_entry.x_roi 
        y = file_entry.y_roi 
        width = file_entry.width_roi 
        height = file_entry.height_roi 

        return render_template('image_selection.html', file=id, x=x, y=y, width=width, height=height)

@main.route('/uploaded_tile_file_preview/<id>')
@login_required
def uploaded_tile_file_preview(id):
    # print("preview_tilefile", str(id))
    # Query the MosaicTiles table for the data where the filename matches
    file_entry = MosaicTiles.query.filter_by(id=id).first()

    if file_entry:

        d = zlib.decompress(file_entry.data)
        img = Image.frombytes("RGB", (file_entry.rows, file_entry.cols), d)
        file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], file_entry.filename)
        img.save(file_path)

        file_data = None
        with open(file_path, 'rb') as f:
            file_data = f.read()

        os.remove(file_path)

        if None != file_data:
            mime_type = mimetypes.guess_type(file_entry.filename)[0]

            if mime_type:
                return send_file(io.BytesIO(file_data), mimetype=mime_type, as_attachment=True, download_name=file_entry.filename)
            else:
                abort(400, description="MIME type could not be determined.")
    else:
        abort(404, description="File not found.")

    return 'File not found', 404

@main.route('/tile_uploads/<id>')
@login_required
def uploaded_tile_file(id):
    # Query the MosaicTiles table for the data where the filename matches
    file_entry = MosaicTiles.query.filter_by(id=id).first()

    if file_entry:

        d = zlib.decompress(file_entry.data)
        img = Image.frombytes("RGB", (file_entry.rows, file_entry.cols), d)
        file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], file_entry.filename)

        left = file_entry.x_roi
        upper = file_entry.y_roi
        right = file_entry.x_roi + file_entry.width_roi
        lower = file_entry.y_roi + file_entry.height_roi

        cropped_img = img.crop((left, upper, right, lower))

        cropped_img.save(file_path)

        file_data = None
        with open(file_path, 'rb') as f:
            file_data = f.read()

        os.remove(file_path)

        if None != file_data:
            mime_type = mimetypes.guess_type(file_entry.filename)[0]

            if mime_type:
                return send_file(io.BytesIO(file_data), mimetype=mime_type, as_attachment=True, download_name=file_entry.filename)
            else:
                abort(400, description="MIME type could not be determined.")
    else:
        abort(404, description="File not found.")

    return 'File not found', 404

@main.route('/mosaic_preview_uploads/<id>')
@login_required
def uploaded_mosaic_image_preview_file(id):
    # Query the MosaicTiles table for the data where the filename matches
    file_entry = MosaicPreviewImages.query.filter_by(id=id).first()

    if file_entry:

        d = zlib.decompress(file_entry.data)
        img = Image.frombytes("RGB", (file_entry.rows, file_entry.cols), d)
        file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], file_entry.filename)
        img.save(file_path)

        file_data = None
        with open(file_path, 'rb') as f:
            file_data = f.read()

        os.remove(file_path)

        if None != file_data:
            mime_type = mimetypes.guess_type(file_entry.filename)[0]

            if mime_type:
                return send_file(io.BytesIO(file_data), mimetype=mime_type, as_attachment=True, download_name=file_entry.filename)
            else:
                abort(400, description="MIME type could not be determined.")
    else:
        abort(404, description="File not found.")

    return 'File not found', 404

@main.route('/mosaic_uploads/<id>')
@login_required
def uploaded_mosaic_image_file(id):
    # Query the MosaicTiles table for the data where the filename matches
    file_entry = Mosaic.query.filter_by(id=id).first()

    if file_entry:
        if None != file_entry.data:
            mime_type = mimetypes.guess_type(file_entry.filename)[0]

            if mime_type:
                d = zlib.decompress(file_entry.data)
                return send_file(io.BytesIO(d), mimetype=mime_type, as_attachment=True, download_name=file_entry.filename)
            else:
                abort(400, description="MIME type could not be determined.")
    else:
        abort(404, description="File not found.")

    return 'File not found', 404

@main.route('/target_uploads/<id>')
@login_required
def uploaded_target_file(id):
    # Query the MosaicTiles table for the data where the filename matches
    file_entry = MosaicTargetImages.query.filter_by(id=id).first()

    if file_entry:

        d = zlib.decompress(file_entry.data)
        img = Image.frombytes("RGB", (file_entry.rows, file_entry.cols), d)
        file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], file_entry.filename)
        img.save(file_path)

        file_data = None
        with open(file_path, 'rb') as f:
            file_data = f.read()

        os.remove(file_path)

        if None != file_data:
            mime_type = mimetypes.guess_type(file_entry.filename)[0]

            if mime_type:
                return send_file(io.BytesIO(file_data), mimetype=mime_type, as_attachment=True, download_name=file_entry.filename)
            else:
                abort(400, description="MIME type could not be determined.")
    else:
        abort(404, description="File not found.")

    return 'File not found', 404

@main.route('/mosaify')
@login_required
def mosaify():
    print("enter mosaify")
    all_projects = Project.query.filter_by(user_id=current_user.id).all()
    projects = [proj.id for proj in all_projects]

    current_project_id = session['current_project_id']
    filenames = MosaicTiles.query.with_entities(MosaicTiles.filename, MosaicTiles.id).filter_by(project_id=current_project_id).all()
    files = [file.id for file in filenames]

    target_filenames = MosaicTargetImages.query.with_entities(MosaicTargetImages.filename, MosaicTargetImages.id).filter_by(project_id=current_project_id).all()
    target_files = [file.id for file in target_filenames]

    mosaic_image_preview = MosaicPreviewImages.query.with_entities(MosaicPreviewImages.id).filter_by(project_id=current_project_id).first()
    mosaic_image_preview_id = None
    if mosaic_image_preview and len(mosaic_image_preview) > 0:
        mosaic_image_preview_id = mosaic_image_preview[0]

    mosaic_image = Mosaic.query.with_entities(Mosaic.id).filter_by(project_id=current_project_id).first()
    mosaic_image_id = None
    if mosaic_image and len(mosaic_image) > 0:

app/templates/home.html
<!-- /*
* Template Name: Snap
* Template Author: Untree.co
* Tempalte URI: https://untree.co/
* License: https://creativecommons.org/licenses/by/3.0/
*/ -->
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'pre.html' %}
    <script>
      function deleteProject(projectId) {
        fetch(`/delete_project/${projectId}`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
        })
          .then((response) => response.json())
          .then((data) => {
            if (data.success) {
              // Remove the image from the gallery
              document.getElementById(`project-${projectId}`).remove();
              location.reload();
            } else {
              alert(data.message);
            }
          });
      }
    </script>
  </head>
  <body>
    <main>
      <section class="site-section" id="section-blog">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-md-8">
              <div class="row">
                <h2 class="heading" data-aos="fade-up">Projects</h2>
                <div class="col-md-12 mb-4" data-aos="fade-up">
                  <div class="d-md-flex d-block blog-entry align-items-start">
                    <div class="row form-group">
                      <div class="col-md-12">
                        <a
                          href="{{ url_for('main.mosaify_new') }}"
                          class="btn btn-primary btn-md"
                          >Create Project</a
                        >
                        <!-- <input
                          onclick="{{ url_for('main.mosaify_new') }}"
                          type="button"
                          value="Create Project"
                          class="btn btn-primary btn-md"
                        /> -->
                      </div>
                    </div>
                    <!-- <button onclick="{{ url_for('main.mosaify_new') }}">
                      Create Project
                    </button> -->
                    <!-- <div class="mr-0 mr-md-5 mb-3 img-wrap">
                      <a href="#"
                        ><img
                          src="images/img_1.jpg"
                          alt="Image"
                          class="img-fluid mb-0"
                      /></a>
                    </div> -->
                    <!-- <div>
                      <h2 class="mt-0 mb-2">
                        <a href="#"
                          >Lorem ipsum dolor sit amet consectetur adipisicing
                          elit</a
                        >
                      </h2>
                      <div class="meta mb-3">
                        Posted by Ben Jones on <a href="#">Jan 18, 2019</a>
                      </div>
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit. Officiis aliquid doloremque qui, saepe alias eum?
                      </p>
                    </div> -->
                  </div>
                </div>

                {% if projects|length > 0 %} {% for project in projects %}
                <div
                  id="project-{{ project.id }}"
                  class="col-md-12 mb-4"
                  data-aos="fade-up"
                >
                  <div class="d-md-flex d-block blog-entry align-items-start">
                    <div class="mr-0 mr-md-5 mb-3 img-wrap">
                      <a
                        href="{{ url_for('main.mosaify_previous', project_id=project.id) }}"
                        ><img
                          src="{{ url_for('static', filename='images/project.jpeg') }}"
                          alt="Image"
                          class="img-fluid mb-0"
                      /></a>
                    </div>
                    <div>
                      <h2 class="mt-0 mb-2">
                        <a
                          href="{{ url_for('main.mosaify_previous', project_id=project.id) }}"
                          >project-{{ project.id }}</a
                        >
                      </h2>
                      <!-- <div class="meta mb-3">
                        Created by {{ current_user.username }} on
                        <a href="#">Jan 18, 2019</a>
                      </div> -->
                      <div class="meta mb-3">
                        Created by {{ current_user.username }}
                      </div>
                      <button
                        class="btn btn-primary btn-md"
                        onclick="deleteProject({{ project.id }})"
                      >
                        Delete
                      </button>
                      <!-- <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit. Officiis aliquid doloremque qui, saepe alias eum?
                      </p> -->
                      <p>{{ project.name }}</p>
                    </div>
                  </div>
                </div>
                {% endfor %} {% else %}
                <div class="col-md-12 mb-4" data-aos="fade-up">
                  <div class="d-md-flex d-block blog-entry align-items-start">
                    <p>No projects available.</p>
                  </div>
                </div>
                {% endif %}

                <!-- 
                NOTICE: Example Item card
                <div class="col-md-12 mb-4" data-aos="fade-up">
                  <div class="d-md-flex d-block blog-entry align-items-start">
                    <div class="mr-0 mr-md-5 mb-3 img-wrap">
                      <a href="#"
                        ><img
                          src="images/img_4.jpg"
                          alt="Image"
                          class="img-fluid mb-0"
                      /></a>
                    </div>
                    <div>
                      <h2 class="mt-0 mb-2">
                        <a href="#"
                          >Lorem ipsum dolor sit amet consectetur adipisicing
                          elit</a
                        >
                      </h2>
                      <div class="meta mb-3">
                        Posted by Ben Jones on <a href="#">Jan 18, 2019</a>
                      </div>
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit. Officiis aliquid doloremque qui, saepe alias eum?
                      </p>
                    </div>
                  </div>
                </div> 
                -->

                <!-- 
                NOTICE: Use for pagination.
                <div class="col-12 text-center">
                  <div class="custom-pagination">
                    <span>1</span>
                    <a href="#">2</a>
                    <a href="#">3</a>
                    <span>...</span>
                    <a href="#">7</a>
                  </div>
                </div> 
                -->
              </div>
              <div class="col-12 text-center">
                <a
                  class="btn btn-primary btn-md"
                  href="{{ url_for('main.logout') }}"
                  >Logout</a
                >
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>

    {% include 'post.html' %}
  </body>
</html>

app/templates/image_selection.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Select Area on Image</title>
    <style>
      .canvas-container {
        position: relative;
        display: inline-block;
      }
      .selection-rectangle {
        position: absolute;
        border: 2px dashed #000;
        pointer-events: none;
      }
    </style>
  </head>
  <body>
    <h1>Select a Square on the Image</h1>
    <div class="canvas-container">
      <!-- <img id="image" src="https://files.worldwildlife.org/wwfcmsprod/images/HERO_Chimpanzee_Uganda/hero_small/5ww9mfzphi_Medium_WW215321.jpg" alt="Image" style="max-width: 100%;"> -->
      <img
        id="image"
        src="{{ url_for('main.uploaded_tile_file_preview', id=file) }}"
        alt="{{ file }}"
        style="max-width: 100%"
      />
      <div id="selection" class="selection-rectangle"></div>
    </div>
    <button onclick="sendSelection()">Submit Selection</button>
    <a href="{{ url_for('main.list_files') }}">List uploaded files</a>
    <a href="{{ url_for('main.mosaify') }}">Back to upload</a>

    <script>
      function disableDragAndDrop() {
        document.addEventListener("dragstart", function (event) {
          event.preventDefault();
        });

        document.addEventListener("drop", function (event) {
          event.preventDefault();
        });
      }

      // Call the function to disable drag and drop
      disableDragAndDrop();
    </script>
    <script>
        const image = document.getElementById("image");
        const selection = document.getElementById("selection");
        let startX, startY, endX, endY;

        image.addEventListener("load", () => {
          const rect = image.getBoundingClientRect();
          selection.style.left = "{{ x }}px";
          selection.style.top = "{{ y }}px";
          selection.style.width = "{{ width }}px";
          selection.style.height = "{{ height }}px";
        });

        image.addEventListener("mousedown", (e) => {
          const rect = image.getBoundingClientRect();
          const startX = Math.max(0, e.clientX - rect.left);
          const startY = Math.max(0, e.clientY - rect.top);
          selection.style.left = startX + "px";
          selection.style.top = startY + "px";
          selection.style.width = "0px";
          selection.style.height = "0px";
          selection.style.display = "block";

          function onMouseMove(e) {
              const endX = Math.min(rect.width, Math.max(0, e.clientX - rect.left));
              const endY = Math.min(rect.height, Math.max(0, e.clientY - rect.top));

              // Calculate width and height based on mouse movement
              let width = endX - startX;
              let height = endY - startY;

              // Ensure that width and height form a perfect square
              const size = Math.min(Math.abs(width), Math.abs(height));
              width = size * Math.sign(width);
              height = size * Math.sign(height);

              selection.style.width = Math.abs(width) + "px";
              selection.style.height = Math.abs(height) + "px";
              selection.style.left = width < 0 ? startX + width + "px" : startX + "px";
              selection.style.top = height < 0 ? startY + height + "px" : startY + "px";
          }

          function onMouseUp() {
              document.removeEventListener("mousemove", onMouseMove);
              document.removeEventListener("mouseup", onMouseUp);
          }

          document.addEventListener("mousemove", onMouseMove);
          document.addEventListener("mouseup", onMouseUp);
      });

        function sendSelection() {
          const rect = selection.getBoundingClientRect();
          const imgRect = image.getBoundingClientRect();
          const x = rect.left - imgRect.left;
          const y = rect.top - imgRect.top;
          const width = rect.width;
          const height = rect.height;
          const _id = {{ file }}

          fetch("/process_selection", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ x, y, width, height, _id }),
          })
            .then((response) => response.json())
            .then((data) => {
              console.log("Selection data:", data);
            });
        }
    </script>
  </body>
</html>

app/templates/index.html
<!-- /*
* Template Name: Snap
* Template Author: Untree.co
* Tempalte URI: https://untree.co/
* License: https://creativecommons.org/licenses/by/3.0/
*/ -->
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'pre.html' %}
  </head>
  <body>
    <main>
      <section class="vh-100">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6 text-black">
              <div class="px-5 ms-xl-4">
                <i
                  class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4"
                  style="color: #709085"
                ></i>
                <span class="h1 fw-bold mb-0">Mosaify</span>
              </div>

              <div
                class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5"
              >
                <form
                  method="POST"
                  action="{{ url_for('main.login') }}"
                  style="width: 23rem"
                >
                  <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px">
                    Log in
                  </h3>

                  <div data-mdb-input-init class="form-outline mb-4">
                    <input
                      type="email"
                      name="email"
                      id="email"
                      class="form-control form-control-lg"
                      required
                    />
                    <label class="form-label" for="form2Example18"
                      >Email address</label
                    >
                  </div>

                  <div data-mdb-input-init class="form-outline mb-4">
                    <input
                      type="password"
                      name="password"
                      id="password"
                      class="form-control form-control-lg"
                      required
                    />
                    <label class="form-label" for="form2Example28"
                      >Password</label
                    >
                  </div>

                  <div class="pt-1 mb-4">
                    <button
                      data-mdb-button-init
                      data-mdb-ripple-init
                      class="btn btn-info btn-lg btn-block"
                      type="submit"
                    >
                      Login
                    </button>
                  </div>

                  <p class="small mb-5 pb-lg-2">
                    <a class="text-muted" href="#!">Forgot password?</a>
                  </p>
                  <p>
                    Don't have an account?
                    <a href="{{ url_for('main.register') }}">Register here</a>
                  </p>
                </form>
              </div>
            </div>
            <div class="col-sm-6 px-0 d-none d-sm-block">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img3.webp"
                alt="Login image"
                class="w-100 vh-100"
                style="object-fit: cover; object-position: left"
              />
            </div>
          </div>
        </div>
      </section>
    </main>

    {% include 'post.html' %}
  </body>
</html>

app/templates/list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Uploaded Images</title>
    <script>
      function deleteImage(imageId) {
        fetch(`/delete_tileimage/${imageId}`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
        })
          .then((response) => response.json())
          .then((data) => {
            if (data.success) {
              // Remove the image from the gallery
              document.getElementById(`file-${imageId}`).remove();
            } else {
              alert(data.message);
            }
          });
      }
    </script>
  </head>
  <body>
    <div>
      <h1>Uploaded Images</h1>
      <ul>
        {% for file in files %}
        <li>
          <div id="file-{{ file }}">
            <a href="{{ url_for('main.preview_tilefile', id=file) }}">
              <img
                src="{{ url_for('main.uploaded_tile_file', id=file) }}"
                alt="{{ file }}"
                style="max-width: 200px"
              />
            </a>

            <p>{{ file }}</p>
            <button onclick="deleteImage({{ file }})">Delete</button>
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
    <a href="{{ url_for('main.mosaify') }}">Back to upload</a>
  </body>
</html>

app/templates/login.html
<!-- /*
* Template Name: Snap
* Template Author: Untree.co
* Tempalte URI: https://untree.co/
* License: https://creativecommons.org/licenses/by/3.0/
*/ -->
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'pre.html' %}
  </head>
  <body>
    <main>
      <section class="vh-100">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6 text-black">
              <div class="px-5 ms-xl-4">
                <i
                  class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4"
                  style="color: #709085"
                ></i>
                <span class="h1 fw-bold mb-0">Mosaify</span>
              </div>

              <div
                class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5"
              >
                <form
                  method="POST"
                  action="{{ url_for('main.login') }}"
                  style="width: 23rem"
                >
                  <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px">
                    Log in
                  </h3>

                  <div data-mdb-input-init class="form-outline mb-4">
                    <input
                      type="email"
                      name="email"
                      id="email"
                      class="form-control form-control-lg"
                      required
                    />
                    <label class="form-label" for="form2Example18"
                      >Email address</label
                    >
                  </div>

                  <div data-mdb-input-init class="form-outline mb-4">
                    <input
                      type="password"
                      name="password"
                      id="password"
                      class="form-control form-control-lg"
                      required
                    />
                    <label class="form-label" for="form2Example28"
                      >Password</label
                    >
                  </div>

                  <div class="pt-1 mb-4">
                    <button
                      data-mdb-button-init
                      data-mdb-ripple-init
                      class="btn btn-info btn-lg btn-block"
                      type="submit"
                    >
                      Login
                    </button>
                  </div>

                  <p class="small mb-5 pb-lg-2">
                    <a class="text-muted" href="#!">Forgot password?</a>
                  </p>
                  <p>
                    Don't have an account?
                    <a href="{{ url_for('main.register') }}">Register here</a>
                  </p>
                </form>
              </div>
            </div>
            <div class="col-sm-6 px-0 d-none d-sm-block">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img3.webp"
                alt="Login image"
                class="w-100 vh-100"
                style="object-fit: cover; object-position: left"
              />
            </div>
          </div>
        </div>
      </section>
    </main>

    {% include 'post.html' %}
  </body>
</html>

app/templates/post.html
<script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-migrate-3.0.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.easing.1.3.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-ui.js') }}"></script>
<script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/owl.carousel.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.stellar.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.countdown.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/aos.js') }}"></script>
<script src="{{ url_for('static', filename='js/lozad.min.js') }}"></script>

<script src="{{ url_for('static', filename='js/jquery.fancybox.min.js') }}"></script>

<script src="{{ url_for('static', filename='js/main.js') }}"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->